### ISSUE TITLE
How to add contextual data to all logs

### ISSUE THREAD

**Issue by brlima94** [newrelic/newrelic-logenricher-dotnet#99]
## Is your feature request related to a problem? Please describe.
In our current integration with New Relic Logs, we add contextual data to facilitate troubleshooting and reporting in dashboards.
This includes, for instance:
* Static data (container IP, environment labels)
* Dynamic data (user id, internal transaction id)

## Feature Description
We need the ability to add contextual (static and dynamic) data so they appear as separate fields in New Relic Logs to facilitate query.

## Describe Alternatives
For now the only way I found to make this work is by creating another layout deriving from NewRelicJsonLayout, but this is not a maintainable long-term solution.
The changes I made to make this work were:
* Modify these properties which are hardcoded to false in current code: `                IncludeMdc = true,
                IncludeMdlc = true,`
* Use MappedDiagnosticsContext for static info: `MappedDiagnosticsContext.Set("Message.Properties.labels.version", "from env var");`
* Use MappedDiagnosticsLogicalContext for dynamic info: `MappedDiagnosticsLogicalContext.Set($"Message.Properties.UserId", "from request, retrieved in Middleware/Filter");`

## Additional context
I think a good way to have this would be with a wrapper class that internally adds these fields in MappedDiagnosticsContext/MappedDiagnosticsLogicalContext with the "Message.Properties." prefix.
Similar to the deprecated NewRelic.Api.Agent.NewRelic.AddCustomParameter.

Another option could be to add this into a scoped context class, but it would require additional DI setup which can be avoided by using MappedDiagnosticsContext/MappedDiagnosticsLogicalContext.

**Note:** it is important to be able to separate between static (set at startup based on env vars) and dynamic (set during request), including both in all logs.

## Priority
**Blocker** - for as much as we want to migrate to JSON layout for distributing tracing, we can't do it without maintaining parity for our dashboards who heavily depend on NRQL.

**Comment by lspangler584** [comment]
@brlima94 Thank you for the great description and ideas you provided for this Issue. I am moving out of Triage and in to Backlog so that it can be prioritized.

**Comment by dtabuenc** [comment]
Is there a reason these are turned off explicitly? Can't you just allow them to be turned on just like it currently does allow you to turn off the Global Diagnostic Context?

**Comment by jaffinito** [comment]
@dtabuenc
I believe that we were trying to limit the payload to just the message specific data and the linking metadata from the agent.  In hindsight, this seems like an error.

@brlima94
We are going to be working on this feature in a short while and I wanted to fill you in and get your feedback on our current plans.

- We are going to remove the hard coded blocks on IncludeMdc, IncludeMdlc, and IncludeAllProperties from [here](https://github.com/newrelic/newrelic-logenricher-dotnet/blob/57dfd189700d8ab85dccfbaa7efac81318541b73/src/NewRelic.LogEnrichers.NLog/NewRelicJsonLayout.cs#L96-L98).
- We are going to leave the defaults for those same settings as found [here](https://github.com/newrelic/newrelic-logenricher-dotnet/blob/57dfd189700d8ab85dccfbaa7efac81318541b73/src/NewRelic.LogEnrichers.NLog/NewRelicJsonLayout.cs#L66-L68).
- We are going to update the NLog example to include methods to configure those settings.
- We are going to be looking at the .NET agent specific documentation to see if we can improve it as well.

I wanted discuss how the new MDC/MDLC data is going to appear in our JSON and in New Relic One.
When the includes are set to true, any key-value pairs they contain will be serialized into JSON just like everything else and added as additional attributes to the JSON log.  These can be filtered and queried just like any other attribute using NRQL.

Here is an example of what the JSON reports now:
```
{"timestamp":1625613422488,"log.level":"INFO","message":"This is log message #0","message.template":"This is log message #{MessageID}","logger.name":"Example","thread.id":"1","process.id":"30432","Message.Properties":{"MessageID":0},"trace.id":"ZZZ","span.id":"YYYY","entity.name":"Logging.NLog.Examples","entity.type":"SERVICE","entity.guid":"XXXX","hostname":"testing123"}
````

Here is what it will look like with MDC and MDLC enabled:
```
{"timestamp":1625613422489,"log.level":"INFO","message":"This is log message #0","message.template":"This is log message #{MessageID}","logger.name":"Example","thread.id":"1","process.id":"30432","Message.Properties":{"MessageID":0},"mdc-prop":"mdc-First Transaction","mdlc-prop":"mdlc-First Transaction","trace.id":"ZZZ","span.id":"YYYY","entity.name":"Logging.NLog.Examples","entity.type":"SERVICE","entity.guid":"XXXX","hostname":"testing123"}
```

In the feature description, you mentioned including these in Message.Properties.  Our usage of Message.Properties is meant for structured logging argument data and not this type of information.   There is also no distinction between MDC and MDLC data since everything is an attribute and can be filtered or queried.

**Comment by brlima94** [comment]
Hi @jaffinito ,

Thanks for the detailed explanation, I thought "Message.Properties" prefix was needed, didn't realize it was due to structured logging at that time.

Your example looks like what I'm expecting, just confirming:
- The JSON output you showed is result of 2 MDC/MDLC entries added with "mdc-prop" and "mdlc-prop" keys?
- These would be accessible in NR Logs and NRQL as "mdc-prop" and "mdlc-prop" without any extra setup, except for log forwarding?
- How are these going to be customizable (enabled) going forward? Through code in app startup or in NLog.Config? We want to make sure this is one of our first lines of code so all logs are printed with the environment labels we need

If my understanding is correct, I think your implementation will address our needs.

**Comment by jaffinito** [comment]
Hey @brlima94 

- Yes, the example was from one of each MDC/MDLC.
- Yes, it should just work.
- The "lnclude" settings can be updated in code.  I don't know if they can be changed in the NLog.config, I have only ever used the code method to set things up.

If you want to see how this is shaping up you can see the PR with the update example [here](https://github.com/newrelic/newrelic-logenricher-dotnet/pull/108). (and the actual update PR [here](https://github.com/newrelic/newrelic-logenricher-dotnet/pull/107))
